#!/bin/bash
# Removes the original PNG/JPG images that were replaced by WebP versions.
# Run from the repo root: bash remove_old_images.sh
set -e
git rm -q --ignore-unmatch "assets/images/about.png"
git rm -q --ignore-unmatch "assets/images/hero-bg.jpg"
git rm -q --ignore-unmatch "assets/images/iso26.png"
git rm -q --ignore-unmatch "assets/images/logo/reliant-gear-icon.png"
git rm -q --ignore-unmatch "assets/images/logo/reliant-logo-compact.png"
git rm -q --ignore-unmatch "assets/images/logo/reliant-logo-full.png"
git rm -q --ignore-unmatch "assets/images/featured_projects/assembly.jpg"
git rm -q --ignore-unmatch "assets/images/featured_projects/setup.png"
git rm -q --ignore-unmatch "assets/images/featured_projects/stamping.jpg"
git rm -q --ignore-unmatch "assets/images/industries/agriculture/item1.png"
git rm -q --ignore-unmatch "assets/images/industries/agriculture/item2.png"
git rm -q --ignore-unmatch "assets/images/industries/agriculture/item3.png"
git rm -q --ignore-unmatch "assets/images/industries/medical/item1.png"
git rm -q --ignore-unmatch "assets/images/industries/medical/item2.png"
git rm -q --ignore-unmatch "assets/images/industries/transportation/item1.png"
git rm -q --ignore-unmatch "assets/images/industries/transportation/item2.png"
git rm -q --ignore-unmatch "assets/images/industries/transportation/item3.png"
git rm -q --ignore-unmatch "assets/images/industries/transportation/item4.png"
git rm -q --ignore-unmatch "assets/images/industries/transportation/item5.png"
git rm -q --ignore-unmatch "assets/images/industries/transportation/item6.png"
git rm -q --ignore-unmatch "assets/images/industries/transportation/item7.png"
git rm -q --ignore-unmatch "assets/images/industries/transportation/item8.png"
git rm -q --ignore-unmatch "assets/images/posters/capabilities-facts.jpg"
git rm -q --ignore-unmatch "assets/images/posters/coil-handling.jpg"
git rm -q --ignore-unmatch "assets/images/posters/hero-reliant.jpg"
git rm -q --ignore-unmatch "assets/images/posters/press-chute.jpg"
git rm -q --ignore-unmatch "assets/images/posters/press-operator.jpg"
git rm -q --ignore-unmatch "assets/images/posters/press-verson.jpg"
git rm -q --ignore-unmatch "assets/images/posters/press-wide-clearing.jpg"
git rm -q --ignore-unmatch "assets/images/posters/quality-fixture.jpg"
git rm -q --ignore-unmatch "assets/images/posters/quality-inspection.jpg"
git rm -q --ignore-unmatch "assets/images/posters/tooling.jpg"
git rm -q --ignore-unmatch "assets/images/posters/welding-station.jpg"
git rm -q --ignore-unmatch "assets/images/team/grilling.jpeg"
git rm -q --ignore-unmatch "assets/images/team/july4th.jpg"
git rm -q --ignore-unmatch "assets/images/team/managers.jpg"
git rm -q --ignore-unmatch "assets/images/team/team.jpg"
git rm -q --ignore-unmatch "assets/images/landing/img1.jpg"
git rm -q --ignore-unmatch "assets/images/landing/img2.jpg"
git rm -q --ignore-unmatch "assets/images/landing/img3.png"
git rm -q --ignore-unmatch "assets/images/clients/client1.png"
git rm -q --ignore-unmatch "assets/images/clients/client2.png"
git rm -q --ignore-unmatch "assets/images/clients/client3.png"
git rm -q --ignore-unmatch "assets/images/clients/client4.png"
git rm -q --ignore-unmatch "assets/images/clients/client5.png"
git rm -q --ignore-unmatch "assets/images/clients/client6.png"
git rm -q --ignore-unmatch "assets/images/clients/client7.png"
git rm -q --ignore-unmatch "assets/images/clients/client8.png"
echo "Old images removed. Now run: git add -A && git commit -m \"convert images to WebP\" && git push"
